let todos = [
{
    text: 'milk',
    complete: false,
    priority: 1,
    today: true,
    tomorrow: false,
    personal: true,
    work: false,
    regular: true,
    important: false,
    id: 0,
},

{
    text: `bread`,
    complete: true,
    priority: 2,
    today: true,
    tomorrow: false,
    personal: true,
    work: false,
    regular: true,
    important: false,
    id: 1,
},

{
    text: 'cheese',
    complete: false,
    priority: 2,
    today: true,
    tomorrow: false,
    personal: true,
    work: false,
    regular: true,
    important: false,
    id: 2,
},

{
    text: 'potatoes',
    complete: false,
    priority: 1,
    today: true,
    tomorrow: false,
    personal: true,
    work: false,
    regular: true,
    important: false,
    id: 3,
},

{
    text: 'pasta',
    complete: true,
    priority: 2,
    today: true,
    tomorrow: false,
    personal: true,
    work: false,
    regular: true,
    important: false,
    id: 4,
},

{
    text: 'bananas',
    complete: true,
    priority: 1,
    today: true,
    tomorrow: false,
    personal: true,
    work: false,
    regular: true,
    important: false,
    id: 5,
},
]
